
# Configuration de la base de données
db.url=jdbc:mysql://localhost:3306/mediplatform_test_test
db.user=root
db.password=
db.driver=com.mysql.cj.jdbc.Driver


String apiKey = System.getenv("GROQ_API_KEY");


gemini.api.key=AIzaSyD6_dXdgw1IDZNKjrM_AivVoRQpGp-H2aY
gemini.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent
paypal.client.id=Adv7qMFA_bJBQmHNX8wM5EITTuKUyalzV_0xcj-Nz7ON-EvTauDR4HlrGvkiKPcMPQlALeliPRcPijlj
paypal.client.secret=ECFQsGaLRCfN4kimntiTOzb9vYQu51QUYMR2qwGjOnBbAHKQwsRSlP8bCaD8gxUXhtlJrDCrjTDu52oM
paypal.mode=sandbox