# Configuration de la base de données
db.url=jdbc:mysql://localhost:3306/mediplatform_test_test?connectTimeout=5000&socketTimeout=5000
db.user=root
db.password=
db.driver=com.mysql.cj.jdbc.Driver

# Groq API (Chat IA) — get your key at https://console.groq.com
groq.api.key=
groq.model=llama-3.3-70b-versatile
groq.api.url=https://api.groq.com/openai/v1/chat/completions

# Gemini API
gemini.api.key=AIzaSyD6_dXdgw1IDZNKjrM_AivVoRQpGp-H2aY
gemini.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent

# PayPal
paypal.client.id=Adv7qMFA_bJBQmHNX8wM5EITTuKUyalzV_0xcj-Nz7ON-EvTauDR4HlrGvkiKPcMPQlALeliPRcPijlj
paypal.client.secret=ECFQsGaLRCfN4kimntiTOzb9vYQu51QUYMR2qwGjOnBbAHKQwsRSlP8bCaD8gxUXhtlJrDCrjTDu52oM
paypal.mode=sandbox
